"""empty message

Revision ID: cbb905bee7f5
Revises: c1998f4f2e4a
Create Date: 2020-09-28 11:13:02.611057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb905bee7f5'
down_revision = 'c1998f4f2e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=25), nullable=True))
        batch_op.add_column(sa.Column('qualification', sa.String(length=50), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('psycologists', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psycologists', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=25), nullable=True))
        batch_op.drop_column('qualification')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
