"""empty message

Revision ID: dc2efea0832a
Revises: cbb905bee7f5
Create Date: 2020-09-29 14:12:42.212072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc2efea0832a'
down_revision = 'cbb905bee7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('education', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('experiance', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('experiance')
        batch_op.drop_column('education')

    # ### end Alembic commands ###
